services:
  backend:
    build: ./sampleproject
    container_name: spring-boot-backend
    ports:
     - '8080:8080'
  frontend:
    build: ./sampleprojectfrontend
    container_name: react-frontend
    ports:
      - '5173:5173'